### ISSUE TITLE
在弹窗中选择字体、大小等下拉框不可见

### ISSUE THREAD

**Issue by cebrains** [caiya/vue-neditor-wrap#1]
在弹窗中，附加富文本控件，控件中的下拉框点击都不正常，在对话框下方展示，希望解决。

**Comment by caiya** [comment]
@cebrains 这个需要修改neditor，可以给neditor项目组提bug

**Comment by cebrains** [comment]
你好，我两边都提问了，他们让我找这个项目，您这边让我找他们，这我就不知道干啥了
