### ISSUE TITLE
vue2.0怎么使用错误

### ISSUE THREAD

**Issue by fadeds** [caiya/vue-neditor-wrap#12]
vue2.0放到静态资源之后   报错    没有配置上去   应该是暴露方式问题

**Comment by caiya** [comment]
这个是vuecli3下的配置，2.0的应该是放到static下面



caiya928@aliyun.com
 
发件人： fadeds
发送时间： 2019-06-06 21:25
收件人： caiya/vue-neditor-wrap
抄送： Subscribed
主题： [caiya/vue-neditor-wrap] vue2.0怎么使用错误 (#12)
vue2.0放到静态资源之后 报错 没有配置上去 应该是暴露方式问题
―

**Comment by love-zhen** [comment]
@caiya  你好，我是用的是 vuecli2.0 修改了 `UEDITOR_HOME_URL`的参数为`/static/NEditor/`便可以使用了，没有报错，是不是可以了呢？还是有其他坑?

**Comment by caiya** [comment]
@love-zhen 能显示了一般就没啥了，剩下的bug就要去neditor官方提了

**Comment by love-zhen** [comment]
@caiya 好的，谢谢
