### ISSUE TITLE
TypeError: Cannot read property 'style' of null

### ISSUE THREAD

**Issue by MorisHarA** [caiya/vue-neditor-wrap#27]
![image](https://user-images.githubusercontent.com/22467182/127588362-5e247c50-76d5-42ea-9bc5-01834021b0b8.png)

**Comment by MorisHarA** [comment]
本地开发环境是好的，打包完部署就出现这个情况

**Comment by ZhangZhiH** [comment]
同问

**Comment by ZhangZhiH** [comment]
> 本地开发环境是好的，打包完部署就出现这个情况

我解决了 是标签 有个name标签 没有 定义

**Comment by MorisHarA** [comment]
> 本地开发环境是好的，打包完部署就出现这个情况

解决了 发现vue我是使用的最新的2.6.14，vue 2.6.13版本以后就不支持script裸奔了，外面得套个div
[https://github.com/vuejs/vue/releases](url)
![image](https://user-images.githubusercontent.com/22467182/129177748-fa4ffcc7-c641-464c-8f7a-34a7c2adf611.png)

**Comment by ZhangZhiH** [comment]
> > 本地开发环境是好的，打包完部署就出现这个情况
> 
> 解决了 发现vue我是使用的最新的2.6.14，vue 2.6.13版本以后就不支持script裸奔了，外面得套个div
> [https://github.com/vuejs/vue/releases](url)
> ![image](https://user-images.githubusercontent.com/22467182/129177748-fa4ffcc7-c641-464c-8f7a-34a7c2adf611.png)

是的 我也加了个div 顺便去掉了哪个没有用的name....然后就好了 我以为是name 的原因
