### ISSUE TITLE
配置了serverUrl 没有请求服务器获取config  上传图片用不了

### ISSUE THREAD

**Issue by zkamisama** [caiya/vue-neditor-wrap#3]
配置了serverUrl 没有请求服务器获取config  上传图片用不了

**Comment by caiya** [comment]
@zkamisama serverUrl是不用配置的，具体的配置在service.js里面，有详细介绍

**Comment by zkamisama** [comment]
@LuSir001  你可以在service.js 里面的setFormData处理上传数据中添加token
