### ISSUE TITLE
v-model 有问题，导致出现空内容的情况

### ISSUE THREAD

**Issue by qiuguanyou** [caiya/vue-neditor-wrap#8]
```
// v-model语法糖实现
  watch: {
    value: {
      handler(value) {
        
          this.editor ? this._setContent(value) : this._beforeInitEditor(value);
        
      },
      immediate: true
    }
  }
```
bug 修复代码
```
  // v-model语法糖实现
  watch: {
    value(value){
      this.editor ? this._setContent(value) : this._beforeInitEditor(value);
    }
  }
```

**Comment by Tfz1024** [comment]
可不可以把这个bug在vue-neditor-wrap改一下   因为我们项目是用Jenkins自动化编译的  都是主动去github上拉取，希望能改个版本再放上github

**Comment by caiya** [comment]
已经merge request

**Comment by Tfz1024** [comment]
ok  感谢




------------------ 原始邮件 ------------------
发件人: "西安-晁州"<notifications@github.com>; 
发送时间: 2019年8月1日(星期四) 下午4:31
收件人: "caiya/vue-neditor-wrap"<vue-neditor-wrap@noreply.github.com>; 
抄送: "Jane"<1032861834@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [caiya/vue-neditor-wrap] v-model 有问题，导致出现空内容的情况 (#8)




已经merge request
 
&mdash;

**Comment by shaodushu** [comment]
@caiya 代码中immediate还是没有去掉😂
